export const products = [
  {
    id: 0,
    name: "Boss Package",
    image: "./products/boss-package.jpg",
    quantity: 0,
    rating: "4.8/5",
    currentPrice: 119.00,
    listPrice: 245.00,
  },
  {
    id: 1,
    name: "Champion Package",
    image: "./products/champion-package.jpg",
    quantity: 0,
    rating: "4.5/5",
    currentPrice: 79.00,
    listPrice: 103.00,
  },
  {
    id: 2,
    name: "Fusions & Stage 6 Parts",
    image: "./products/fusions-stage-6-parts.jpg",
    quantity: 0,
    rating: "4.2/5",
    currentPrice: 60.00,
    listPrice: 60.00,
  },
  {
    id: 3,
    name: "Utah Flash Duality Package",
    image: "./products/utah-flash-duality-package.jpg",
    quantity: 0,
    rating: "4.5/5",
    currentPrice: 35.00,
    listPrice: 79.00,
  },
];
